### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jiadesen** [pengzhanbo/vite-plugin-mock-dev-server#1]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/22772994/210149723-43f7b092-a42d-4a08-972a-588d606543fb.png">

**Comment by jiadesen** [comment]
vite4+vue3

**Comment by jiadesen** [comment]
vite3 启动报相同的错误..老哥你自测通过了么==、

**Comment by jiadesen** [comment]
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import mockDevServerPlugin from 'vite-plugin-mock-dev-server'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    mockDevServerPlugin(),
  ],
  server: {
    proxy: {
      '^/api': 'http://example.com/',
    },
  },
})

```

把 `vue()` 删掉就不报错了，这个插件不能跟 `@vitejs/plugin-vue` 共存？

**Comment by jiadesen** [comment]
`build` 参数 `define` 类型错误引起的，提了个 pr 有时间看看

<img width="568" alt="image" src="https://user-images.githubusercontent.com/22772994/210170570-7a7f8ad3-9770-4d73-a023-e649ed822646.png">

**Comment by pengzhanbo** [comment]
[vite define] 文档中的描述是 define 的配置， string 值会以原始表达式形式使用，所以如果定义了一个字符串常量，它需要被显式地打引号。（例如使用 JSON.stringify）。 以及 为了与 [esbuild 的行为](https://esbuild.github.io/api/#define)保持一致，表达式必须为一个 JSON 对象（null、boolean、number、string、数组或对象），亦或是一个单独的标识符。

基于文档的说明，所以我没有对 define 传入的配置做特殊的处理。 在我重新阅读了 vite 相关的代码， 在定义的 [vite:define](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/define.ts#L34) 时，对非  `string` 类型进行了 `JSON.stringify` 处理。 

这里是我没有考虑到的。
