### ISSUE TITLE
能否开放或提供一种支持用户自定义扩展服务器的功能配置

### ISSUE THREAD

**Issue by itmanyong** [pengzhanbo/vite-plugin-mock-dev-server#103]
### 新特性说明

主要是想要支持某些服务器默认不自带的功能时需要用户自行给予扩展
目前的问题是 DELETE 请求类型需要携带body，而目前模拟server得到的body为undefined

### 解决方案建议

1.默认内置所有请求类型的全参数类型(query、params、body)解析
2.对外暴露扩展服务器server功能的配置

**Comment by pengzhanbo** [comment]
1. 虽然 RFC7231 并没有明确规定 DELETE 不能携带请求体。通常来说 DELETE 请求并不会携带 body ，而且多数的服务器或者客户端的实现也可能不支持或者忽略 DELETE 中的 body。这也是为什么插件内在解析 body 时默认忽略了 DELETE 请求。对于需要通过 body 携带更多数据的请求，我更推荐的做法是使用 POST 请求代替，而非通过 method 实现语义化。
2. 关于解析 body 时忽略 DELETE ，我会在下个版本中删除该项。

3. 是否暴露 server 扩展功能的选项，这个在很早前我就有考虑过了。插件并没有实现一个新的 server，而仅是在 vite 的 dev server 上做的扩展，因此所有对 vite 开发服务的扩展也都可以作用于 mock 插件，但这也需要考虑到中间件的顺序问题。我在最开始的时候是有添加此选项的想法的，但是这里引入了一个新的问题，即插件是支持单独构建一个可运行的 mock-server 项目的，这里也需要加载 插件的配置，然而插件的配置是写在 vite.config.ts 中的，插件内部需要将插件的用户配置序列化，然而一般 server 的扩展要么是一个第三方的依赖，要么是一个 函数，这就导致了这部分很难被序列化。而如果要解决这个问题，就需要将插件的配置写到一个单独的文件中。但关于是否有必要这么做，我很难下判断，至少在我实际的使用中，以及插件发布以来，并没有收到相关的功能请求。而且 mock 重点关注的是返回期望的响应数据、headers 中是否有必要的声明，这些在mock 配置中都能够很好的得到解决，必须通过 server 扩展来添加功能的场景至少我是没有碰到过的。
