### ISSUE TITLE
缺失 isObject 方法

### ISSUE THREAD

**Issue by SunLxy** [pengzhanbo/vite-plugin-mock-dev-server#104]
### Bug 描述

这个包里面使用了`isObject`方法名。但是在最新的`@pengzhanbo/utils`里面把`isObject`方法名换成了`isPlainObject`。
<img width="788" alt="image" src="https://github.com/user-attachments/assets/656d42f1-c8d2-4f0d-a815-3aae063c7da9">

### 系统环境

```markdown
- OS:
- Node:
- packageManager:
- vite:
- vite-plugin-mock-dev-server:
```

**Comment by pengzhanbo** [comment]
一般而言 现代包管理器都会锁定依赖版本，不应该出现此问题。🤔

**Comment by SunLxy** [comment]
删除了 lock 文件。重新补依赖
