### ISSUE TITLE
热更新和参数问题

### ISSUE THREAD

**Issue by kenixFog** [pengzhanbo/vite-plugin-mock-dev-server#15]
1、环境：v0.4.0 + vue 2.7.14 + vite 4.1.3
2、问题
1）开发环境，修改***.mock.ts文件接口数据，好像无法热更新
2）是否可支持属性同义词配置，比如，axios中 params 表示 url后的参数，data表示body体的参数，但实际mock接口接收后，query、params、body无法对应，是否可支持同义词配置？alias : { body：'data',  query:  'params'}

**Comment by pengzhanbo** [comment]
1. 重新进行了自测，热更新是有效的，修改后接口重新返回的数据有更新。

    接口数据的热更新是体现在重新发起请求后获取的数据，由于接口请求热更新的局限性，很难实现`mock.ts`文件更新后自动让客户端重新发起请求，所以在不同场景下，可能需要开发者手动刷新页面，或者进行其他触发二次请求的操作。
关于这一点，我可以实现一个新的 `reload` option，让开发者决定 mock 更新是否强制刷新客户端以重新发起请求。

3. mock 配置中的 `query`，`params`，`body`，没有与 `axios` 中的 `params`，`data` 对应，是由于 插件对 `url` 的解析方式支持两种模式： 
    - `{ url: '/api/list' }` ，这种模式下， `url` 是一个静态的配置
    - `{ url: '/api/post/:postId' }`, 这种模式下， `url` 是一个动态路由匹配， 既可以命中 `/api/post/1`, 也可以命中 `/api/post/2`

    在这两种模式下，`url` 均可以带上查询参数，如： `/api/list?page=2`， `/api/post/1?type=2`。 为了能够加以区分，提取出 `url` 中包含的两种携带的数据，插件选择了将 `?page=2`，`?type=2` 这部分 `queryString` 解析为 `query`, 而 `/api/post/:postId`的动态路由匹配，则解析为 `params` ，即 `{ postId: 1 }`。这样做可以避免冲突，也更好理解。

     同时插件考虑是支持通过各种方式发起的请求，包括但不限于 `axios`，所以主要考虑的是 遵循 `http`协议的规范。

     添加同义词配置我认为没有意义，反而会增加理解成本，而且还会导致 `defineMock` 提供的类型帮助失效。

**Comment by kenixFog** [comment]
1、可能是我本地环境问题，有空再试一下
2、第二个，怎么说呢~~目前实际开发过程中，想达到一个url请求，比如设定以mock开头的，是有可能要走mock的接口，但实际是否启用mock，是结合开发和测试环境的其它环境变量参数进行控制的，也就是一个定义的url是根据配置最终处理成执行时的url，从而适配开发+mock接口、开发+后端接口，测试+mock接口，测试+后端接口4种情况，如果选择以axios的方式，现在的插件是无法获取到相应的参数的，而传参的格式必须是根据插件规定的方式来，相当于需要针对mock接口对参数进行特殊处理，至于其它方式发请求，还没尝试。感觉如果要更加灵活，达到支持各种方式发起的请求（至少目前axios请求的参数拿不到，应该算是不支持哈），增加同义词，相比较只能按照http规范来，不失为一种可以考虑的手段~

**Comment by pengzhanbo** [comment]
可否给出使用 axios 和 mock 的相关代码示例？

**Comment by kenixFog** [comment]
1、请大佬检阅~~
环境，v0.4.0 + vue 2.7.14 + vite 4.1.3 + Axios 1.3.3 + typescript 4.9.5，
2、vite.config.ts中插件的配置
```
import { resolve } from 'path'
import mockDevServerPlugin from 'vite-plugin-mock-dev-server'

export function initMockDevServerPlugin() {
  return mockDevServerPlugin({
    prefix: 'mock',
    include: 'mock/**/*.mock.{ts,js,cjs,mjs,json,json5}',
    formidableOptions: {
      // 配置上传资源存放目录
      uploadDir: resolve(process.cwd(), 'uploads'),
      // 可修改上传资源名称
      filename: (name, ext, part) => {
        return part.originalFilename!
      },
    },
    build: {
      serverPort: 6666,
      dist: 'mockServer',
    },
  })
}
```
3、api.mock.ts:
```
import { defineMock } from 'vite-plugin-mock-dev-server'
export default defineMock([
  {
    url: '/mock/caseCache/getData',
    body: (res, query, params, body) => {
      console.log(res)
      return {
        data: {
          query,
          params,
          body,
          isLogin: true,
        },
        message: '成功',
        code: '200',
      }
    },
  },
])
```
4、请求接口
```
import { request } from '@/utils/request'

const url = {
  getData: '/mock/proxyTest/caseCache/getData',
}

export function ApiGetSectionData(params, data): Promise<Jsonable> {
  return request.get<Jsonable>(
    {
      params,
      data,
      url: url.getData,
    },
    {
      requireAuth: false,
      messageMode: 'message',
      actionType: 'query',
    },
  )
}
```
ps:
1） url会根据配置，自动移除mock，或者proxyTest
2） params和data，对应axios中AxiosRequestConfig接口的params和data类型
```
export interface AxiosRequestConfig<D = any> {
  url?: string;
  method?: Method | string;
  baseURL?: string;
  transformRequest?: AxiosRequestTransformer | AxiosRequestTransformer[];
  transformResponse?: AxiosResponseTransformer | AxiosResponseTransformer[];
  headers?: (RawAxiosRequestHeaders & MethodsHeaders) | AxiosHeaders;
  params?: any;
  paramsSerializer?: ParamsSerializerOptions;
  data?: D;
  timeout?: Milliseconds;
  ……
```
5、实际请求
```
const querySection = async () => {
  const data = await ApiGetSectionData(
    {
      name: 1234,
      date1:
      DateUtil.getDateTime(),
    },
    {
      date2: DateUtil.getDateTime(),
    },
  )
  console.log(data)
}
```
6、请求结果
![Snipaste_2023-02-23_21-49-18](https://user-images.githubusercontent.com/29566225/220930146-e1648a6c-587d-4fd1-9ee8-5f3e1f8097fd.png)

如果图片无法加载，可以浏览器访问这个地址，https://imgse.com/i/pSxojHA

**Comment by pengzhanbo** [comment]
> 3、api.mock.ts:
>```
>import { defineMock } from 'vite-plugin-mock-dev-server'
>export default defineMock([
>  {
>    url: '/mock/caseCache/getData',
>    body: (res, query, params, body) => {   ❌
>      console.log(res)
>      return {
>        data: {
>        query,
>          params,
>          body,
>          isLogin: true,
>        },
>        message: '成功',
>        code: '200',
>      }
>    },
>  },
>])
>```
这里有一个错误: method `body` 只接收一个参数 `resquest`, `query, params, body` 是 `resquest` 参数的属性，可以通过解构语法获取：
```ts
{
  body: (resquest) => {
    const { query, params, body } = request
  }
}
```
```ts
{
  body: ({ query, params, body }) => {
    
  }
}
```
----

> 6、请求结果
> ![](https://user-images.githubusercontent.com/29566225/220930146-e1648a6c-587d-4fd1-9ee8-5f3e1f8097fd.png)

从截图中我看到的有两个问题点， 一个是 响应体中的 `body` 为 `undefined` ，一个是反馈的 `isLogin` 没有更新。

问题1产生的原因是 `request.headers['content-type']` 值为 `application/json;charset:UTF-8` 导致内部未能匹配到跳过了解析，这个是 插件bug，我会进行修复；
问题2产生的原因，有可能是浏览器的默认缓存策略影响，我会尝试加上 `cache-control: no-store,max-age=0`，但我在本地测试，以及在 StackBlitz 搭建的 `playground` 测试，热更新均有效的。

你可以尝试在你的 `scripts` 中加上一段 `DEBUG=vite:plugin-mock-dev-server`：
```json
{
  "dev": "DEBUG=vite:plugin-mock-dev-server vite"
}
```
然后重新启动，对 mock文件进行修改， 修改后控制台会有如下信息提示，则说明热更新是成功的

![image](https://user-images.githubusercontent.com/16745751/220954471-46b1a793-d5f2-4284-9845-958e27959dcf.png)

然后在浏览器控制台，`network` 中，勾选禁用缓存，尝试下数据是否有更新。 
请给我上述内容的情况反馈，我好方便进一步定位问题，谢谢

**Comment by pengzhanbo** [comment]
以上发现的问题已在 `v0.4.2` 版本中修复，升级插件版本即可。

**Comment by pengzhanbo** [comment]
结合一下你提的：
> 2、第二个，怎么说呢~~目前实际开发过程中，想达到一个url请求，比如设定以mock开头的，是有可能要走mock的接口，但实际是否启用mock，是结合开发和测试环境的其它环境变量参数进行控制的，也就是一个定义的url是根据配置最终处理成执行时的url，从而适配开发+mock接口、开发+后端接口，测试+mock接口，测试+后端接口4种情况....

我想给你一些使用 vite 和 mock插件的一些建议。

一般来说，前端在开发环境，请求后端的开发环境接口，常常会遇到的情况是跨域问题，这也是为什么`vite` 有 `server.proxy` 的原因之一，它可以很好的帮助前端将接口通过 vite的开发服务转发到后端的开发服务中。而在大多数需要mock的场景中，也是由于后端的开发接口尚未准备好，前端期望并行开发所以需要通过mock数据来模拟。所以 `server.proxy`配置的代理转发，和 需要mock的接口往往是具有相同的路径的，这也是为什么这个插件会选择直接使用 `server.proxy` 的配置的直接原因。

可以很方便的实现，在一个 `localhost:4375` 的 `vite` 开发服务下 , 在前端的代码中， 如进行一个 `axios.get('/api/post/list')` 的请求，请求链接为 `http://localhost:4375/api/post/list` ，如果配置了 `{ proxy: { '^/api': { target: 'http://dev-backend.com' } } }`, 那么 `vite` 会将请求转发到 `http://dev-backend.com/api/post/list` ，当vite有使用到这个 mock 插件，那么 mock插件会在 `proxy` 代理之前，拦截这个请求，使用 `*.mock.*` 配置的 `/api/post/list` 的数据返回给前端，还可以通过 `enable` 控制是否开启对这个接口的mock。

这里就可以很直观的看出，在不修改前端源码的前提下，开发环境就可以很灵活的控制是走 mock的拦截，还是走 `proxy` 的转发。

那么其实没有必要在项目源码中做是否走 `mock` 的控制，实际的接口请求地址怎么的，还是按照实际的写即可。

而对于测试环境需要使用到 mock 数据， 插件提供的 可独立部署的mock服务，启动后，通常不应该直接请求它，而是应该根据 前端部署情况，比如部署在 通过 `nginx` 提供的 http 服务，那么应该在该 `nginx` 对应的 端口配置下，新增一个 `location` 配置做代理转发到 mock 服务中，以保持 源码中的接口请求路径不会受环境变化而发生改变。

对于接口请求路径，不同环境，可接受的变化范围，应该只有 `域+端口+前缀`，这部分应该通过 `vite` 提供的 `env` 来控制，通过 `define` 注入到源码中。

此外，插件还提供了一个 `referQuery` 的 `validator` 配置， 它可以让你在浏览器地址栏中修改页面的 queryString 来灵活的控制 `mock` 数据内容，它非常适合解决 团队协作的场景，以及 通过浏览器地址栏控制 当前页面mock不同的数据。

希望这些建议对你有所帮助。

**Comment by kenixFog** [comment]
> 以上发现的问题已在 `v0.4.2` 版本中修复，升级插件版本即可。

上面的问题，都已经解决~~

遇到个新"问题"，但是不晓得能不能从插件层面进行容错~~

```
body: (res, query, params, body) => {   ❌
```

这个修改的时候，我改错了，我写成了

```
(body: (res,  {query, params, body} ) => {)
```

然后导致程序直接退出
```

E:\0WorkSpace\app\mock\api.mock.ts:30
    body: (res, { query, params, body }) => {
                  ^

TypeError: Cannot destructure property 'query' of 'undefined' as it is undefined.
    at Object.body (E:\0WorkSpace\app\mock\api.mock.ts:30:19)
    at E:\0WorkSpace\app\node_modules\.pnpm\vite-plugin-mock-dev-server@0.4.2_vite@4.1.4\node_modules\vite-plugin-mock-dev-server\dist\index.cjs:456:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.6.0
 ELIFECYCLE  Command failed with exit code 1.
```

这个写法肯定有问题，但万一手抖，改错了。。重新启动，时间成本略微有点高~

**Comment by pengzhanbo** [comment]
@kenixFog 我将这个新问题转移到新的 issue #17 。
