### ISSUE TITLE
功能请求：希望可以对所有MockOptionsItem中的字段url添加前缀

### ISSUE THREAD

**Issue by 2509989976** [pengzhanbo/vite-plugin-mock-dev-server#23]
### 希望的api：

1.在vite.config.js中的mockDevServerPlugin中新增加配置选项urlPrefix，用于指定mock的url前缀  
或者在mockDevServerPlugin中新增加配置选项urlRewrite，用于指定mock的url重写规则  
或是直接读取vite.config.js中的server.proxy中的rewrite规则

```
export default defineConfig({
	plugins: [
		mockDevServerPlugin({
		    urlPrefix:'/api',
		    //或者
		    urlRewrite: (path) => path.replace(/^\/api/, ''),
		})
	],
	server: {
		proxy: {
			'/api': {
				target: "http://example.com",
				rewrite: (path) => path.replace(/^\/api/, ''),
			}
		}
	}
})
```

2.改造defineMock，添加第二个参数，用于指定MockOptionsItem的url前缀

```
defineMock([{
    url:'/login'
    ...
}，{
    url:'/logout'
    ...
}], {
    urlPrefix:'/api/user'
})
```

### 解决的问题
1.proxy中的key一般情况下并不是直接存在于api的url中，而是用户为了统一代理而添加的一个自定义前缀，比如/api，/api2，/api3等等  
但是在mock中如果每一项都添加一个/api的话，会导致mock的url和真实的url看起来不一致，而且麻烦，所以希望能够统一指定一个前缀
2.在同一个mock文件中，一般都是同一类的api,例如user相关的api,一般都会以/user开始。

以上只是部分使用场景的举例，我感觉如果将此功能加入后，会更加方便，也更加灵活。

### 争议点
当defineMock中的urlPrefix选项和mockDevServerPlugin中的urlPrefix或urlRewrite都存在时，应该以哪个为准? 或者是同时生效?

**Comment by pengzhanbo** [comment]
首先感谢提出新的功能。

**1.：** 
`urlPrefix/urlRewrite`无论是作为一个字符串还是一个返回一个字符串的函数，它的预期表现可能不会如你的期望。

试想以下情况，在 `server.proxy` 中配置了 `{ '^/api1': '/proxy-1/', '^/api2': '/proxy-2/' }` ，一个还未配置 `urlPrefix` 的 mock url 为 `/api1/test`,  当配置了 `urlPrefix` 为 `/api` ，那么 预期的 mock url 可以简写为 `test`。

但是有一个潜在的问题，`server.proxy` 有多个 key， 那么 `urlPrefix` 应该如何判断 简写的 `test` 应该补全 `/api1` 还是 `/api2`。 这可能需要在 简写的 url 中，用别名的方式，重新映射补全 url，这反而不够直观了。

`server.proxy[key].rewrite` 的作用与 `urlRewrite` 是不同的，`server.proxy[key].rewrite` 是重写代理地址到真实的请求地址，类似 `nginx` 配置中的 路径重写，它的作用，是让 开发环境的请求路径，能够和其他环境（测试、生产）保持一致。


**2. ：**
在 `defineMock` 新增第二个参数用于做扩展配置，这个功能是可行的。这个功能可以认为是对第一个功能的优化方案。
我会将它列入到下个版本的功能规划中。

**Comment by 2509989976** [comment]
> 首先感谢提出新的功能。
> 
> **1.：** 无论是作为一个字符串还是一个返回一个字符串的函数，它的预期表现可能不会如你的期望。`urlPrefix/urlRewrite`
> 
> 试想以下情况，在 中配置了 ，一个还未配置 的 mock url 为 ， 当配置了 为 ，那么 预期的 mock url 可以简写为 。`server.proxy``{ '^/api1': '/proxy-1/', '^/api2': '/proxy-2/' }``urlPrefix``/api1/test``urlPrefix``/api``test`
> 
> 但是有一个潜在的问题， 有多个 key， 那么 应该如何判断 简写的 应该补全 还是 。这可能需要在 简写的 url 中，用别名的方式，重新映射补全 url，这反而不够直观了。`server.proxy``urlPrefix``test``/api1``/api2`
> 
> `server.proxy[key].rewrite`的作用与 是不同的， 是重写代理地址到真实的请求地址，类似 配置中的 路径重写，它的作用，是让 开发环境的请求路径，能够和其他环境（测试、生产）保持一致。`urlRewrite``server.proxy[key].rewrite``nginx`
> 
> **2. ：** 在 新增第二个参数用于做扩展配置，这个功能是可行的。这个功能可以认为是对第一个功能的优化方案。 我会将它列入到下个版本的功能规划中。`defineMock`

那是否可信增加一个方法，用于创建一个新的defineMock方法呢？
就像vue3中的useXXX或createXXX一样
示例如下：

```
export const defineApiMock = createDefineMock({
    urlPrefix:'/api',
})

export const defineApi2Mock = createDefineMock({
    urlPrefix:'/api2',
})

defineApiMock([{
    url:'/logout',
    ...
},{
    url:'/logout',
    ...
}],{
    urlPrefix:'/user',
})

```

这样，用户就可以在不同的mock中重用了。既不影响您所说的1中的问题，同时也重用了代码。  
不同的前缀使用不同的defineMock方法即可。

**Comment by 2509989976** [comment]
我对您的改进表示认同，这样确实会更加灵活，扩展性也会更强。

**Comment by pengzhanbo** [comment]
`createDefineMock` 已在 `v1.0.7` 版本中添加支持
