### ISSUE TITLE
raw html response from file

### ISSUE THREAD

**Issue by pySilver** [pengzhanbo/vite-plugin-mock-dev-server#24]
Hello! 

Is that possible to respond with raw `html` file from an actual file? My goal is to emulate response delays while adding some specific response headers when dev server is pointed to few specific locations.

p.s. Thanks for the interesting plugin!

**Comment by pengzhanbo** [comment]
The plugin supports the full node.js development capability. For responses that require complete customization, you can use the `response` option for configuration.
```ts
export default defineMock({
  response(req, res, next) {
    // req is the Node.js http request object
    // res is the Node.js http response object
    // next is a function to call to invoke the next middleware
    // do something
  }
})
```
In this method, you can get the request information through the `req` parameter, such as `req.url`, etc., and match specific resources through the URL. Then add response headers through `res.setHeader(key, value)`.
Finally, call `res.end(body)` to respond to the request, or if no resources are matched, call the `next()` method to hand the request processing over to other middleware.

The `response` method provides development capabilities equivalent to **Connect middleware**. Please refer to the [official documentation](https://github.com/senchalabs/connect#use-middleware).

I hope this answer can help you. If you have any other questions, please ask and I will do my best to assist you.

**Comment by pySilver** [comment]
@pengzhanbo thanks for such a detailed reply! I've managed to accomplish my task (though it took me a while to notice that this middleware is different than I've used in BrowserSync where I could simply modify header and pass through request with `next()`


```js
import { defineMock } from 'vite-plugin-mock-dev-server'
import fs from 'fs'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const turboStreamResponse = (req, res) => {
  const page = resolve(__dirname, '../src/') + req._parsedUrl.pathname
  fs.readFile(page, (err, data) => {
    if (err) throw err
    res.status = 200
    res.setHeader('Content-Type', 'text/vnd.turbo-stream.html')
    res.end(data)
  })
}

export default defineMock([
  {
    url: '/_partials/product/list-2.html',
    delay: 1000,
    response(req, res, next) {
      turboStreamResponse(req, res)
    },
  },
  {
    url: '/_partials/product/list-3.html',
    delay: 1000,
    response(req, res, next) {
      turboStreamResponse(req, res)
    },
  },
  {
    url: '/_partials/facet/form_response.html',
    delay: 3000,
    response(req, res, next) {
      turboStreamResponse(req, res)
    },
  },
  {
    url: '/_partials/_dummy_turbo_response.html',
    delay: 1000,
    response(req, res, next) {
      turboStreamResponse(req, res)
    },
  },
])
```

Works like charm!
