### ISSUE TITLE
关于mock前置拦截功能

### ISSUE THREAD

**Issue by Xjinzz** [pengzhanbo/vite-plugin-mock-dev-server#27]
环境：
vite3+vue3

问题描述：
我不想频繁操作vite.config文件，看到您官网上有一个【enable】属性，但是写了enable属性后，会导致ts报错如下：
<img width="804" alt="image" src="https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/24968460/73d3c94b-808c-42b9-84d3-0e1061c33007">
并且，只要写了enable之后不管写true还是false都不走mock了

期望：
1、有一个拦截函数，类似于下面格式
const mockEnable = false
export default mockFilter({ url, params, body, query, xxx }) :Boolean => {})
export default defineMock({  xxxxxxx })
2.修复enable功能
3.修复ts报错

**Comment by pengzhanbo** [comment]
对于报错信息的截图，我有两点疑惑：
1. 插件并没有 `mode` 的配置项，`找不到名称 ”mode“` 的错误信息是否可以先排查下来源？
2. 函数重载错误，一般是由于使用了函数不支持的参数，从而导致了 重载错误。

在插件提供的 配置中, 用于控制是否启用当前mock配置的属性是 `enabled` ，我仔细检查了我编辑的文档，发现是我提供的文档中 错误的写成了 `enable` ，这个是我疏忽导致，十分抱歉。 也可能是这个原因导致了 重载错误。

最后关于 您的期望 部分中的 `mockFilter`，插件的 mock 配置中，有一个 `validator` 的配置，它的作用就是进一步根据请求中携带的 `headers`, `query`, `params`, `body` 等信息，根据这些数据判断是否匹配当前的 mock 配置。 `validator` 应该能够满足 `mockFilter` 的期望表现。 相关示例可以查看 [validator](https://vite-plugin-mock-dev-server.netlify.app/examples/validator)

**Comment by pengzhanbo** [comment]
另外在本次排查中，还发现一个 bug，不确定是否跟你的问题有关联。大概跟你描述下。

当mock配置中有以下两个类似的配置文件时时：
``` ts
// a.mock.ts
export default defineMock({
  url: '/api/post/:postId'
})
```
``` ts
// b.mock.ts
export default defineMock({
  url: '/api/post/list'
})
```
如果 `a.mock.ts` 优先于 `b.mock.ts` 被解析加载，那么客户端发起的 `/api/post/list` 的请求，会总是命中 `a.mock.ts` 中的配置，而不是命中期望的`b.mock.ts`的配置，这是由于 `/api/post/list` 也是符合 `/api/post/:postId` 的解析匹配的。

这个问题也可能会导致对 `b.mock.ts` 的配置使用 `enabled` ，也不会有预期表现。
