### ISSUE TITLE
1.1.6版本开始`transform`排序规则存在问题

### ISSUE THREAD

**Issue by jiadesen** [pengzhanbo/vite-plugin-mock-dev-server#28]
这里为啥由2改为了1

<img width="727" alt="image" src="https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/22772994/2c72590c-05e2-4ebf-ac21-f74dfd20f399">

**Comment by pengzhanbo** [comment]
emmm，当时我应该是在开发 websocket mock 的支持，然后脑子一下子没想起来一开始为什么设置为 2，就给改成了 1，我的问题 😂 。

**Comment by jiadesen** [comment]
例如下边 mock 文件

> validator-refererQuery.mock.ts
```
import { defineMock } from 'vite-plugin-mock-dev-server'
import postList from './data/post'

// Different pages send the same interface and can get different
// data through the query parameter of the source page
export default defineMock([
  // default
  {
    url: '/api/post/list',
    body: {
      list: ['default'],
    },
  },
  // localhost/post.html?from=post-page
  // send request /api/post/list
  {
    url: '/api/post/list',
    validator: {
      refererQuery: { from: 'post-page' },
    },
    body: {
      list: ['post'],
    },
  },
  // localhost/recommend.html?from=recommend-page
  // send request /api/post/list
  {
    url: '/api/post/list',
    validator: {
      refererQuery: { from: 'recommend-page' },
    },
    body: {
      list: ['recommend'],
    },
  },
])
```

`mocks` 顺序差异：

- 返 1：['default', 'post', 'recommend']
- 返 2：['post', 'recommend', 'default']

返 1 会直接导致上述 mock 文件的 `validator` 失效（`0` 位置存在 `default` 则始终返回 `default` 数据）

**Comment by pengzhanbo** [comment]
@jiadesen 是的，post 和  recommend 的优先级计算均为 1， 而 default 的优先级计算也是 1 （应该为 2），当均为 1 的时候，默认以 配置书写的顺序，所以就是 ['default', 'post', 'recommend']。
