### ISSUE TITLE
BUG(response error): appendHeader is not a function

### ISSUE THREAD

**Issue by 1night2zero** [pengzhanbo/vite-plugin-mock-dev-server#29]
### My code like this:
```typescript
{
    url: `${BASE_URL}/xxx`,
    method: ['POST'],
    response: (req, res) => {
      const { username, password } = req.body
      if (xxx === 'xxx' && yyy === 'yyy') {
        res.statusCode = 200
        res.setHeader('Content-Type', 'application/json')
        res.appendHeader('Set-Cookie', 'xxx=xxx; Path=/; HttpOnly')
        res.end(
            .....
        )   
      }eles if(...){
        ...
      }
    }
}
``` 

### Error message:
```shell
mock-dev-server:  [response error] /mock-api/xx/xx 
 file: mock/test.mock.ts TypeError: res.appendHeader is not a function
    at response (/home/xx/Desktop/xx/mock/test.mock.ts:54:13)
    at /home/xx/Desktop/xx/node_modules/.pnpm/registry.npmmirror.com+vite-plugin-mock-dev-server@1.1.13_vite@4.3.5/node_modules/vite-plugin-mock-dev-server/dist/index.cjs:46:105
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It was working fine the last commit

## version

```shell
node -v
v16.16.0
pnpm -v
8.3.1
vite-plugin-mock-dev-server
1.1.13
typescript
5.0.4
```

**Comment by pengzhanbo** [comment]
The [`res.appendHeader`](https://nodejs.org/dist/latest-v20.x/docs/api/http.html#outgoingmessageappendheadername-value) method is supported starting from `node 16.17.0`, which cannot be used in your `node 16.16.0` that you are using.

If you need to add cookies to the response, you can use [`res.setCookie(name, value, option)`](https://github.com/pengzhanbo/vite-plugin-mock-dev-server#requestresponse-enhance) provided by the plugin.

**Comment by 1night2zero** [comment]
thx

在 2023-05-23 12:49:10，pengzhanbo ***@***.***> 写道：

The res.appendHeader method is supported starting from node 16.17.0, which cannot be used in your node 16.16.0 that you are using.
If you need to add cookies to the response, you can use res.setCookie(name, value, option) provided by the plugin.
