### ISSUE TITLE
文件上传接口报错

### ISSUE THREAD

**Issue by jiadesen** [pengzhanbo/vite-plugin-mock-dev-server#3]
Error: Unsupported content-type: multipart/form-data; boundary=----WebKitFormBoundaryJBADTbzOOrlYZerZ

**Comment by jiadesen** [comment]
整个开发服务都会挂掉

**Comment by pengzhanbo** [comment]
我在 http server 中，针对 `text/plain` ，`application/json` , `application/x-www-form-urlencoded` 的类型类型进行的解析，对未知的其他类型使用了 `co-body` 默认的解析方法。

但 `multipart` 类型，由于其复杂性，很难对其 `body` 进行解析，需要根据应用场景进行特性处理。这在 `parer-body` 、`co-body` 等库中，都是不支持对该类型进行解析的。

开发服务挂掉，是由于 `co-body` 不支持该类型，导致的问题，我会对未知的 `content-type` 类型，修改为默认不解析，返回 undefined。

而对于 `multipart` 类型的内容，比如需要做 文件上传，建议可以通过 Mock 的 `response` 做自定义响应体处理。
```ts
{
    response(req, res, next) {
        // do something
    }
}
```

并且建议可以使用 [busboy](https://www.npmjs.com/package/busboy#readme) 或者 [multiparty](https://www.npmjs.com/package/multiparty#readme) 等库 处理该类型的内容。

**Comment by pengzhanbo** [comment]
我在 http server 中，针对 text/plain ，application/json , application/x-www-form-urlencoded 的类型类型进行的解析，对未知的其他类型使用了 co-body 默认的解析方法。

但 multipart 类型，由于其复杂性，很难对其 body 进行解析，需要根据应用场景进行特性处理。这在 parer-body 、co-body 等库中，都是不支持对该类型进行解析的。

开发服务挂掉，是由于 co-body 不支持该类型，导致的问题，我会对未知的 content-type 类型，修改为默认不解析，返回 undefined。

在我新发布的 `0.3.10` 版本中，添加了 `formidable` 库，用于处理 `multipart` 类型，现在可以使用于 文件上传接口的模拟了，文件对应的字段，会映射为一个 `formidable.File` 的对象，可以查看 [formidable](https://www.npmjs.com/package/formidable#readme) 获取更多使用信息。

**Comment by jiadesen** [comment]
最新版 `0.3.12` 存在更严重的问题，在 `vite^4.0.4` 开发服务启动时就报错了...我也帮你看看吧
```
failed to load config from /Users/xxx/project/vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xxx/project/node_modules/.pnpm/formidable@3.2.5/node_modules/formidable/src/index.js from /Users/xxx/project/node_modules/.pnpm/vite-plugin-mock-dev-server@0.3.12_rollup@3.9.1+vite@4.0.4/node_modules/vite-plugin-mock-dev-server/dist/index.cjs not supported.
Instead change the require of index.js in /Users/xxx/project/node_modules/.pnpm/vite-plugin-mock-dev-server@0.3.12_rollup@3.9.1+vite@4.0.4/node_modules/vite-plugin-mock-dev-server/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object._require.extensions.<computed> [as .js] (file:///Users/xxx/project/node_modules/.pnpm/vite@4.0.4_less@4.1.3+terser@5.16.1/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
    at Object.<anonymous> (/Users/xxx/project/node_modules/.pnpm/vite-plugin-mock-dev-server@0.3.12_rollup@3.9.1+vite@4.0.4/node_modules/vite-plugin-mock-dev-server/dist/index.cjs:325:33)

```

**Comment by jiadesen** [comment]
版本 `0.3.9` 的处理虽说简单粗暴，但是没有啥问题

**Comment by pengzhanbo** [comment]
原因是 `formidable` 在 `v3` 版本只支持 `type` 为 `module` 的项目，即只能通过 `ESModule` 的方式导入，不支持 `CommonJs` 即使用 `require` 的方式导入，版本回退到 `v2` 的版本就可以支持在 `CommonJs` 中使用了。

因为现在很多开源库越来越多的实行 `pure esmodule` ，放弃了多种模块格式的支持，使得这些模块在 `type` 为 `commonjs` 的项目中无法被使用。由于我个人的几乎所有项目都是 `type`为`module`，未能发现 `formidable` 在 `v3`的 breaking change。
