### ISSUE TITLE
1.2.0版本导致vite启动报错

### ISSUE THREAD

**Issue by jiadesen** [pengzhanbo/vite-plugin-mock-dev-server#34]
<img width="1347" alt="image" src="https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/22772994/2cb73071-a3e8-493c-98cf-e2a4bc36a6ac">

**Comment by jiadesen** [comment]
vite@4.3.9

**Comment by kenixFog** [comment]
啊哈，对头，同样的问题~~注释掉插件就没问题了~

**Comment by pengzhanbo** [comment]
`formidable` 从 `2.1.1` 升级到 `3.4.0` 后，其包从默认的 `{ "type": "commonjs" }` 更新到了 `{ "type": "module" }` ， 导致了插件在 默认的 `{ "type": "commonjs" }` 项目中，不能正确的加载 formidable 依赖，导致了启动失败。

目前已将 `formidable`  回退到 `2.1.1` 版本 以解决该问题。
