### ISSUE TITLE
怎么只在yarn run preview下开启mock数据？不想在其他环境使用mock

### ISSUE THREAD

**Issue by gitoftom** [pengzhanbo/vite-plugin-mock-dev-server#35]

**Comment by pengzhanbo** [comment]
使用 `vite preview` 命令时， 默认的 `mode` 为 `production`， `command` 为 `serve`。 

可以在 `vite.config.ts` 配置文件中，通过 
```ts
const isPreview = mode === 'production' && command === 'serve'
``` 
简单的判定为 预览模式。当为预览模式时，添加 mock 插件即可：
```ts
import { defineConfig } from 'vite'
import mockDevServerPlugin from 'vite-plugin-mock-dev-server'

export default defineConfig(({ mode, command }) => {
  const isPreview = mode === 'production' && command === 'serve'
  return {
     plugins: [ isPreview && mockDevServerPlugin() ],
  }
})
```

**Comment by gitoftom** [comment]
默认是写死了预览模式才能使用mock模拟请求是么？也就是yarn dev启动方式是不能用mock数据得。本来像根据.env里面配置得开关决定yarn dev下能不能用mock的。看来不行

**Comment by pengzhanbo** [comment]
我是根据你的需求描述，推测你想实现的功能，再给的代码示例，说明如何只在 `vite preview` 下启用插件。

插件默认就是支持在 `vite dev` 和 `vite preview` 下都支持模拟请求。 如果你想通过 `.env` 环境变量来控制 是否启用 插件，也一样可以实现你的需求。

在使用 `vite preview` 命令时，再显示指定 mode 模式：
`package.json`:
```json
{
  "scripts": {
    "preview": "vite preview -m preview"
  }
}
```
`.env.preview`:
```sh
USER_MOCK = true
```
`vite.config.ts`:
```ts
import { defineConfig, loadEnv } from 'vite'
import mockDevServerPlugin from 'vite-plugin-mock-dev-server'

export default defineConfig(({ mode, command }) => {
  const env = loadEnv(mode, process.cwd(), '')
  return {
     plugins: [ env.USE_MOCK && mockDevServerPlugin() ],
  }
})
```
也一样可以实现只在 `vite preview` 下启用 mock 插件

**Comment by pengzhanbo** [comment]
需要在什么时候启用mock，完全取决你的需求需要在什么维度下选择是否启用，再根据 `nodejs`和 `vite` 提供的支持，以及你的需求，编写对应的 代码。

**Comment by gitoftom** [comment]
谢谢解答
