### ISSUE TITLE
vite4.x版本中使用别名导致随机性的导入一些方法失败

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [pengzhanbo/vite-plugin-mock-dev-server#36]
我在vite4.x版本中，配置了针对于mock的别名，然后进行一些方法的导入。如果是冷启动的时候，该方法必然会被提示找不到：
<img width="1149" alt="image" src="https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/51957438/b9e91199-92a7-4eb1-a1f3-efe681b1f9e9">
如果我在修改代码后，该导入又是正常的。

这个问题让我很困惑，希望得到解决一下，否则在嵌套层数过深的地方，很不友好。

**Comment by XiaoDaiGua-Ray** [comment]
<img width="1189" alt="image" src="https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/51957438/1b70c81a-4bd0-43e7-a1f7-346962b71b7d">
<img width="1188" alt="image" src="https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/51957438/8253277e-3f60-472a-a408-4c79a17f690a">
这里是代码的一些细节，其实代码并没有报错，也可以直接被点击跳转进去

**Comment by pengzhanbo** [comment]
@XiaoDaiGua-Ray 
目前我在分别在MacOS, Windows， node@18.16， vite@4.4.9 下，均未复现出该问题。

请提供一些详细的信息：
1. 操作系统
2. node 版本
3. vite 版本
4. alias 中 `@mock` 的配置代码

如果方便的话，请提供一个 能够复现该问题的仓库分支。

**Comment by XiaoDaiGua-Ray** [comment]
我好像犯了一个很低级的错误，导致我的别名使用失败。。。
