### ISSUE TITLE
希望可以显式定义 *.mock.ts 文件加载顺序，以便于控制不同文件中 mock 规则优先级。

### ISSUE THREAD

**Issue by pfdgithub** [pengzhanbo/vite-plugin-mock-dev-server#48]
我的场景是，需要在一个单独的文件中定义一些通用 mock 规则，并在其他文件中定义专用规则，希望能优先匹配专用规则。
看到之前的 issue 中有类似的问题，插件文档中也没有相关的描述，希望能添加支持。

https://github.com/pengzhanbo/vite-plugin-mock-dev-server/issues/27#issuecomment-1540326371

> 另外在本次排查中，还发现一个 bug，不确定是否跟你的问题有关联。大概跟你描述下。
> 
> 当mock配置中有以下两个类似的配置文件时时：
> 
> ```ts
> // a.mock.ts
> export default defineMock({
>   url: '/api/post/:postId'
> })
> ```
> 
> ```ts
> // b.mock.ts
> export default defineMock({
>   url: '/api/post/list'
> })
> ```
> 
> 如果 `a.mock.ts` 优先于 `b.mock.ts` 被解析加载，那么客户端发起的 `/api/post/list` 的请求，会总是命中 `a.mock.ts` 中的配置，而不是命中期望的`b.mock.ts`的配置，这是由于 `/api/post/list` 也是符合 `/api/post/:postId` 的解析匹配的。
> 
> 这个问题也可能会导致对 `b.mock.ts` 的配置使用 `enabled` ，也不会有预期表现。

**Comment by pengzhanbo** [comment]
这种场景是支持的。插件提供了多种方式来支持从专用场景到通用场景的逐级匹配。

首先，静态匹配规则总是优先于动态匹配规则的，而 动态匹配中，参数个数少的优先于参数个数多的进行匹配。即，`/api/post/:id`, `/api/post/list`, `/api/post/:id/:other` ，当请求进入时，匹配顺序是 
`/api/post/list`, 
`/api/post/:id`, 
`/api/post/:id/:other`。 

但这里需要注意的是， 如果动态匹配规则类似`/api/post/:id` ，`/api/post/:postId` 这种，虽然规则看似相同，但插件不会将两个认为是相同的规则，这时候则是根据用户的书写的顺序先后做为匹配的优先级判断。

其次，插件还提供了 `validator` 规则，用于更加灵活的匹配。可以从 查询参数， 请求体，请求来源，请求头等多个维度做细致的匹配，具体用法可以查看 [文档](https://vite-plugin-mock-dev-server.netlify.app/guide/mock-config#validator) ，以及[使用示例](https://vite-plugin-mock-dev-server.netlify.app/examples/validator) 。

**Comment by pfdgithub** [comment]
> 首先，静态匹配规则总是优先于动态匹配规则的，而 动态匹配中，参数个数少的优先于参数个数多的进行匹配。

对于同样数量，但不同位置的动态参数，优先级如何呢？
对于除命名参数之外的其他参数模式，优先级又如何呢？

经测试，对于以下 mock 规则，匹配 `/api/a/b/c` 的优先级为: 7 -> 8 -> 3 -> 5 -> 6 -> 2 -> 4 -> 1

```
export default defineMock([
  {
    url: "/api/:a/:b/:c",
    body: 1
  },
  {
    url: "/api/:a/:b/c",
    body: 2
  },
  {
    url: "/api/:a/b/c",
    body: 3
  },
  {
    url: "/api/a/:b/:c",
    body: 4
  },
  {
    url: "/api/a/:b/c",
    body: 5
  },
  {
    url: "/api/a/b/:c",
    body: 6
  },
  {
    url: "/api/a/b/c",
    body: 7,
  },
  {
    url: "/api/(.*)",
    body: 8
  },
]);
```

这个用例还没有包含 ?*+修饰符、前缀后缀、正则表达式等  path-to-regexp 支持的参数模式。
我是在使用 `/api/(.*)` 模式时发现的问题，其他场景没有验证，但很可能也是不符合预期的。

最合理的方式是，通过整合 mock 文件，以便使用数组索引循序控制优先级。 
但一个项目经过长时间的迭代后，会很难追踪分散在不同文件中的 mock 路径。
最简单的方式就是通过显式的优先级控制，明确冲突规则的优先级。

**Comment by pengzhanbo** [comment]
对于 path-to-regexp 支持的各种参数模式，插件目前确实没有实现符合预期的优先级匹配。
为此，我做了一些试验性的开发测试，对于一个存在以下规则配置的项目：
```ts
const rules = [
  '/api/(.*)',
  '/api/(.*)/c',
  '/api/(.*)?',
  '/api/(.*)/:c',
  '/api/:a*',
  '/api/:a+',
  '/api/:a/:b?',
  '/api/a/b/c',
  '/api/:a/b/c',
  '/api/a/:b/c',
  '/api/a/b/:c',
  '/api/a/:b/:c',
  '/api/:a/:b/c',
  '/api/:a/b/:c',
  '/api/:a/:b/:c',
  '/api/a/b/:c{-:d}{-:e}?',
]
```
可能接收到的请求地址包括：
```ts
const urls = [
  '/api/a/b/c',
  '/api/a/c/b',
  '/api/e/f/g',
  '/api/a/e/f',
  '/api/e/b/f',
  '/api/e/f/c',
  '/api/a',
  '/api/e/e/e/e',
  '/api',
  '/api/a/b/c-d-e',
]
```
其中，对于 请求为 `/api/a/b/c` 的 `url`，在 `rules`，满足规则的有:
```ts
const matched = [
  '/api/(.*)',
  '/api/(.*)/c',
  '/api/(.*)?',
  '/api/(.*)/:c',
  '/api/:a*',
  '/api/:a+',
  '/api/a/b/c',
  '/api/:a/b/c',
  '/api/a/:b/c',
  '/api/a/b/:c',
  '/api/a/:b/:c',
  '/api/:a/:b/c',
  '/api/:a/b/:c',
  '/api/:a/:b/:c',
]
```
从优先级上：
1. 无参数的规则优先级最高
2. 参数规则少的优先级高，对于参数数量相同的，根据参数所在位置，参数越靠后的优先级越高
3. 命名参数优先级比非命名参数优先级高
4. 对于 有修饰符 `*+?`, 优先级需要对比无修饰符的参数进行降低，
5. 同位置修饰符， `*` 比 `+` 的优先级低
6. 对于 `(.*)` 的参数规则，无论其出现在任何位置，都拥有该位置的最低优先级，`(.*)?` 比 `(.*)` 优先级更低

符合预期的匹配顺序应该是：
```ts
const sortMatched = [
  '/api/a/b/c',
  '/api/a/b/:c',
  '/api/a/:b/c',
  '/api/:a/b/c',
  '/api/a/:b/:c',
  '/api/:a/b/:c',
  '/api/:a/:b/c',
  '/api/:a/:b/:c',
  '/api/:a+',
  '/api/:a*',
  '/api/(.*)/c',
  '/api/(.*)/:c',
  '/api/(.*)',
  '/api/(.*)?',
]
```
同理，其它的 `url` 匹配顺序如下：
```sh
/api/a/c/b : ["/api/a/:b/:c","/api/:a/:b/:c","/api/:a+","/api/:a*","/api/(.*)/:c","/api/(.*)","/api/(.*)?"] 

/api/e/f/g : ["/api/:a/:b/:c","/api/:a+","/api/:a*","/api/(.*)/:c","/api/(.*)","/api/(.*)?"] 

/api/a/e/f : ["/api/a/:b/:c","/api/:a/:b/:c","/api/:a+","/api/:a*","/api/(.*)/:c","/api/(.*)","/api/(.*)?"] 

/api/e/b/f : ["/api/:a/b/:c","/api/:a/:b/:c","/api/:a+","/api/:a*","/api/(.*)/:c","/api/(.*)","/api/(.*)?"] 

/api/e/f/c : ["/api/:a/:b/c","/api/:a/:b/:c","/api/:a+","/api/:a*","/api/(.*)/c","/api/(.*)/:c","/api/(.*)","/api/(.*)?"] 

/api/a : ["/api/:a/:b?","/api/:a+","/api/:a*","/api/(.*)","/api/(.*)?"] 

/api/e/e/e/e : ["/api/:a+","/api/:a*","/api/(.*)/:c","/api/(.*)","/api/(.*)?"] 

/api : ["/api/:a*","/api/(.*)?"] 

/api/a/b/c-d-e : ["/api/a/b/:c{-:d}{-:e}?","/api/a/b/:c","/api/a/:b/:c","/api/:a/b/:c","/api/:a/:b/:c","/api/:a+","/api/:a*","/api/(.*)/:c","/api/(.*)","/api/(.*)?"] 
```

对于 规则匹配的优先级排序，由于 `*.mock.ts` 可以随意存在多个，单个 `*.mock.ts` 中的 规则也可能存在多个，很难通过简单的对 `*.mock.ts` 的显式声明加载顺序来正确控制 规则的优先级，所以我在开发插件时，就简单的对规则进行了排序，在考虑到大多数项目中，很少会使用很复杂的规则，所以初期也没有完善排序规则。大多数情况下，当前版本的插件是能够满足的。

而对于规则多且复杂的场景，手动维护所有规则的排序也很麻烦，所以目前我就定义了 上述的排序规则，但是对于 手动维护优先级的方案，我目前还没有得出一个满意的方案，当前我的想法是，使用者可以通过一个 数组配置，将部分规则的优先级进行提升，
但是提升到哪个位置，又是一个需要考虑的问题点。

**Comment by pfdgithub** [comment]
提供排序的能力，并不是为了手动维护所有规则的排序。而是作为一种兜底方案，在内置排序规则无法满足的情况下，允许用户介入调整部分规则的排序。
从技术实现上也比较简单，在遍历全部 `*.mock.ts` 文件中的全部规则后，对扫描到的全部规则进行重新排序。比如未明确设置的认为是优先级为零，想提高优先级就设置为正数，想降低优先级就设置为负数。
这样理论上允许无线级别的优先级，用户可以根据自己的使用场景，自行按需定义。

**Comment by pfdgithub** [comment]
对这个 API 有两个疑问：
1. 是否需要提供一个类似于 `global` 配置，但优先级低于默认排序规则的配置？
2. 显式配置 `special` 的前提是，知道某个请求与哪几条规则可能匹配？即 `A: ['B', 'C']` 中的 `B` 和 `C` 并不是一次就能配好的，可能会是配置 `A: [B]` 后发现又匹配了 `C`，于是改为配置 `A: [B, C]`。如果又匹配了 `D` 就以此类推继续修改配置？每次匹配到的具体规则 url 如何获取，自行对比或在 `[vite:mock]` 日志中增加输出？
https://github.com/pengzhanbo/vite-plugin-mock-dev-server/commit/5075716e3288458164905a6c381c4dd57a9664a5#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR132

**Comment by pengzhanbo** [comment]
> 1. 是否需要提供一个类似于 global 配置，但优先级低于默认排序规则的配置？

关于这点我有考虑过，开发者最优先关注的是哪个规则优先生效，对于低优先级的几乎是忽略不计的，同时 配置`global` 的同时，其它的规则优先级已经被降低，对于低优先级的规则排序，我认为默认排序规则已可以满足情况。

> 2. 显式配置 special 的前提是，知道某个请求与哪几条规则可能匹配？即 A: ['B', 'C'] 中的 B 和 C 并不是一次就能配好的，可能会是配置 A: [B] 后发现又匹配了 C，于是改为配置 A: [B, C]。如果又匹配了 D 就以此类推继续修改配置？每次匹配到的具体规则 url 如何获取，自行对比或在 [vite:mock] 日志中增加输出？

关于这点，如果不知道匹配了哪些规则，确实想要调整也无从下手，日志输出是有必要添加的，我计划通过添加一个 日志级别 来控制输出这些信息。

**Comment by pfdgithub** [comment]
https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/main/CHANGELOG.md#132-2023-09-11

`/(.*)` 优先级应该小于 `/api/(.*)` 才对吧？。
`(.*)` 未生效，似乎被识别为`/(.*)`，是否符合预期？

```
[vite:mock] GET /api/xxx  (mock/xxx.mock.ts)
[vite:mock] DEBUG /api/xxx  matches: [ /api/xxx, /(.*), /api/(.*) ]
```

```
export default defineMock([
  {
    url: "/api/(.*)",
    body: {
      success: true,
    },
  },
  {
    url: "/(.*)",
    body: {
      success: false,
    },
  },
  {
    url: "(.*)",
    body: {
      success: false,
    },
  },
]);
```

---

对于后端接口开发完成后，前端才介入开发。或者开发完成后才补充接口 mock 数据的场景。
我们的处理方式是，直接把接口响应 body 保存至对应目录下的 json 文件中，不用手动复制 body 到 *.mock.ts 中。
使用 mock 时，对于静态请求路径，直接 json 文件，简单快捷省事。当然这么用的人可能并不多😁

```
import fs from "fs";
import path from "path";
import process from "process";
import colors from "picocolors"
import { defineMock } from "vite-plugin-mock-dev-server";

const print = (type: string, msg: string) => {
  const date = colors.dim(new Date().toLocaleTimeString());
  const tag = colors.bold("[vite:mock-file]");

  if (type === "error") {
    console.error(`${date} ${colors.red(tag)} ${msg}`);
  } else if (type === "warn") {
    console.warn(`${date} ${colors.yellow(tag)} ${msg}`);
  } else {
    console.info(`${date} ${colors.cyan(tag)} ${msg}`);
  }
};

export default defineMock([
  {
    url: "/api/(.*)",
    response: async (req, res, next) => {
      if (!req.url) {
        return next();
      }

      const reqUrl = new URL(req.url, "http://localhost");
      const mockPath = path.join(process.cwd(), "mock", reqUrl.pathname);
      const mockFile = path.normalize(mockPath) + ".json";

      try {
        const mockContent = await fs.promises.readFile(mockFile, {
          encoding: "utf-8"
        });
        res.end(mockContent);
        print("info", mockFile);
      } catch (err) {
        if (err.code === "ENOENT") {
          print("warn", err);
          res.writeHead(404).end();
        } else {
          print("error", err);
          next(err);
        }
      }
    },
  },
]);
```

**Comment by pengzhanbo** [comment]
计算优先级时， `/(.*)` 和 `/api/(.*)` 均被判断为尾随通配，被认为属于相同优先级了，由于一般配置时，请求都会有一个 前缀如 `/api`， 所以就没有 考虑 `/(.*)` 这种情况。 这种情况我重新处理下。

`(.*)` 和 `/(.*)` 的写法是相同的，插件内部会自动补全规则为绝对路径。

> 直接把接口响应 body 保存至对应目录下的 json 文件中。

这种方案，就是基于文件系统的目录结构来作为 路由 进行处理，如果不考虑如 `/[id].json` 这种文件系统常见的动态参数约定，纯静态处理，加入这个功能很简单，从插件的配置，只需要加入一个配置指定 `mock` 下的某个特定的目录作为根目录即可。
但一般如果要实现基于 文件系统的方案，通常还要考虑 `/[id].json` 这种情况的适配，以及整合到现有的插件的 匹配规则优先级中。
其实在 插件最早期的开发阶段，我就有考虑过基于文件系统的方案，但是认为这种方式对于 接口模拟 并不是很适用。

1. 如果后端是微服务架构，其接口路径，一般会是 `服务名 + 业务 + 功能 + 其它` 的结构组成，还有包括会 经由 网关 作为统一出口，接口路径还可能会带上网关前缀，这就导致可能 路径地址会比较长， 这种情况反映到 文件系统中，就是目录嵌套过深。
2. 常见的开发流程中，一般只是需要对部分接口使用模拟数据，其它接口依然代理转发到后端开发服务，特别是在进入联调阶段后，就可能需要频繁的在用模拟数据/不用模拟数据的状态中切换，而用文件类型系统方案的话，就不好灵活的控制了。

现阶段插件也是支持直接加载 `*.mock.json` 格式的，相比于 文件系统方案来说，差别也不大，所以我也就没有支持 文件类型系统方案了。

**Comment by pfdgithub** [comment]
嗯，基于文件系统目录结构加上约定动态参数处理，这个方案缺点是灵活性不足，优点是实现简单，两三百行代码就能搞定。

之前基于 webpack 实现 mock 时，就是基于文件系统做的，支持 js 和 json 文件。原计划是希望主要使用 CommonJS 的模块能力，调用 js 文件动态 mock 接口。为此还引入了不少 express 的中间件来处理 body cookie 等。
结果几年下来历经几家公司的不同业务模式，使用最多的还是直接保存接口为 json 文件的方式。js 方式只在一定需要分页模拟的场景，和很早之前搞 PWA push 时使用过。
当然，也可能是因为我之前的使用场景，对 mock 的诉求是保证在接口不可用时，可以在本地继续走通业务流程，附带一些开发时的异常流程边界验证。并没有非常灵活的 mock 诉求，所以选用了简单的实现方案。

目前使用 `vite-plugin-mock-dev-server` 过程中，还有一个小痛点，是如何“方便快捷”的实现“批量部分”接口的启用和禁用。使用场景是：
先全量 mock 接口，再随着后端接口逐步实现后，一批一批的禁用某些 mock 规则。或者在后续的功能迭代中，需要重构已实现的接口，这时就需要重新批量启用并修改，某些已禁用的 mock 规则。

目前使用的方式是基于 `exclude` 配置，在文件级别控制启用禁用。也能满足要求但总是需要修改 `vite.config.js` 文件，于是就在 `.env` 文件搞了个配置项进行控制。
之前在基于文件系统做 mock 时，我是在 `mock` 目录下，放了一个 `.mockignore` 文件，用 `.gitignore` 语法配置忽略规则。但同样是在文件级别控制启用禁用，与 `exclude` 配置没有本质上的区别，可能唯一的优势可能就是直观一点：mock 禁用规则与 mock 文件放在一个目录下。😂 

这是另一个问题了，当前的 issue 可以结束了，感谢你的工作。

**Comment by pengzhanbo** [comment]
批量 启用禁用其实借用 `createDefineMock` 这个API来控制，因为这个API是对 mock的预处理，可以在这个利用这个API来配置一个 include enable list 或者 exclude enable list ，然后用它返回的 `defineMock()` 来包装 mock 配置，就可以不用在 vite config 中去频繁修改配置，而且可以控制到 url 级别，而不是文件级别。

```ts
const disableList = ['/api/a']

const defineMock = createDefineMock((mock) => {
	if (disablelist.includes(mock.url)) {
        mock.enabled = false
    }
})

defineMock({
	url: '/api/a',
})
```

`createDefineMock` 这个API 设计的初衷，就是为了提供一种更加灵活的方式，满足不同场景和开发诉求。

**Comment by pfdgithub** [comment]
嗯，用 `createDefineMock` 可以更灵活的控制。
目前我是根据接口路径划分 mock 文件，一般后端接口都是 `Controller` 级别完成或重构的，所以文件级别的启用禁用已经可以满足。
