### ISSUE TITLE
defineConfig不存在，文档是不是没更新？

### ISSUE THREAD

**Issue by WindWilliam** [pengzhanbo/vite-plugin-mock-dev-server#51]
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/23290000/39d238b7-cbad-4932-8c86-48becf3cb07d)

另外，请问一下，export default defineMock()这里是只能导出默认的default方法，还是支持任意导出？

**Comment by pengzhanbo** [comment]
插件不存在 `defineConfig` 方法，这里是我文档写错了。

在 `*.mock.ts` 中，是支持 任意导出 `defineMock` 的。
```ts
export const xxx = defineMock()

export default defineMock()
```

都是支持的。

**Comment by WindWilliam** [comment]
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/23290000/66f53eff-1def-4ead-a7f8-1857ad9c721e)

![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/23290000/c1252587-ecf6-40f4-b20d-7e35c8324f0b)

这里remove对应的接口，提示的是404，我重启了vite，也还是不行，上面的update方法，放到另一个文件里，导出为default可以的。
另外再提一句，文档里代码细节有点问题，find返回的是对象，findIndex才是返回序号😄

**Comment by pengzhanbo** [comment]
目前实现上，单个 `*.mock.*` 文件，使用 `default`或具名导出是二选一，即用了 `default` 就不会检查其他具名导出了。
因为 mock 配置一般使用 default 导出就可以了，而使用 具名导出 通常是出于 语义 的考虑，方便代码分区管理。

**Comment by WindWilliam** [comment]
ok，懂了，我去掉default就好了👍
多谢了，问题都解决了。
