### ISSUE TITLE
next() 无法将 POST 请求转交给 Vite 默认代理中间件

### ISSUE THREAD

**Issue by pfdgithub** [pengzhanbo/vite-plugin-mock-dev-server#52]
使用 response(req, res, next) 自定义处理时，对于 POST 请求，无法通过 next() 方式将请求转交给下一个中间件（Vite 默认代理转发）处理 。浏览器 Network 一直处于 pending 状态，直至超时后 canceled 状态。
对于 GET 请求不受影响，可被 Vite 默认代理转发至目标服务器。应该是因为 mock 插件提取 body 时，消耗了 request 流，造成 post 请求无法转交给后续处理器。

这个链接可以参考一下：
https://github.com/pfdgithub/scaffold-webpack/blob/react/cfg/devServer.js#L63

---

vite.config.js
```
{
  server: {
    proxy: {
        "/api": {
          target: "http://1.2.3.4:5"
        },
    }
  }
}
```

_.mock.js
```
export default defineMock([
  {
    url: "/api/(.*)",
    response: async (req, res, next) => {
      console.log(req.method, req.url);
      next();
    },
  },
]);
```

Network
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/3262762/3ac7c888-f3e3-4117-8f9f-2d86f02e68de)
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/3262762/41a02917-0ace-4bb5-9b8d-0d11712b3d66)
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/3262762/95b7a9fc-4a32-48df-9663-300a5902282b)

**Comment by pfdgithub** [comment]
一个可能得解决方案是，将 body 延迟提取。从直接赋值改为 get 访问器，使用时才提取。但这样需要将 body 的异步提取，改为同步提取，可能还要更换第三方解析库。

也可以简单粗暴一点，允许关闭内置的 body 提取逻辑，这样就不用改动太多了。
https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/main/src/baseMiddleware.ts#L74 

![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/3262762/e99deac8-3ca4-455b-85bb-6f1875051b6b)
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/3262762/abf9c23d-2814-4974-883c-fb7078cf8400)

**Comment by pengzhanbo** [comment]
request 请求流被消耗后，在 `http-proxy` 是有机会重新写入的，但问题是 vite 内部没有暴露 proxy 实例，而在 viteConfig.server.proxy 的配置中，虽然也可以添加 `buffer` 选项的配置重写入流，但由于它目前是一个非函数形式的配置，没有机会根据不同的请求写入不同的数据流。

要解决这个问题，首先需要向 vite 提交一个 feature issue， 尝试将 `buffer` 选项配置添加 函数形式的支持：
```ts
export default {
  server: {
    proxy: {
      '^/api': {
        target: '',
        buffer: (req, res) => stream
      }
    }
  }
}
```
或者在 `resolvedConfig` 中拿到 proxies 实例进行修改。

也可以如你所说，延后 解析 body， 但是代价就是 validator 阶段不能对 body进行过滤验证。

目前我计划分这两个事情同时进行。
1. 通过配置延迟 body解析到 validator 之后，validator 不再 验证body；
2. 向 vite 提交 feature issue，讨论 重写 代理请求流 的解决方案
 （由于 vite 在 5.x-beta 阶段，即使有结果可能也会花费较长时间才能在新版本中使用）

**Comment by pfdgithub** [comment]
加了两条建议，你看看要不要调整下，然后发个 beta 版本我试试？

**Comment by pengzhanbo** [comment]
已调整相关代码并进行了本地验证，并发布了一个 v11.3.4-beta.0 的版本， 可通过 `pnpm add -D vite-plugin-mock-dev-server@next` 进行安装。

**Comment by pfdgithub** [comment]
https://github.com/pengzhanbo/vite-plugin-mock-dev-server/pull/53

试了一下，发现两个问题：
1. 对 ws 代理的处理造成 recoverRequest 未被调用
2. 代理配置了 agent 造成 proxyReq 事件冲突。

**Comment by pengzhanbo** [comment]
发布了一个 v1.3.4-beta.1 的版本

**Comment by pfdgithub** [comment]
验证通过
