### ISSUE TITLE
未配置 vite 的 proxy 参数和插件的 prefix 参数，应输出警告信息。

### ISSUE THREAD

**Issue by pfdgithub** [pengzhanbo/vite-plugin-mock-dev-server#68]
随便配置一个无效的 proxy 就能继续走后续 mock 流程了，期望插件本身不强依赖于 proxy 配置。
虽然可以通过插件的 prefix 配置绕过，但是用起来总是有些奇怪。而如果不配置 prefix 又无法区分哪些是接口请求，哪些是资源请求，等于是允许在 *.mock.js 文件中拦截全部请求，也不太合适。
有没有什么好办法支持这种场景呢？🤔

也许应该在检测到 proxy 和 prefix 都未配置时，打印一个警告提醒一下用户？

**Comment by pengzhanbo** [comment]
> 随便配置一个无效的 proxy 就能继续走后续 mock 流程了，期望插件本身不强依赖于 proxy 配置。

其实 `prefix` 配置就已经实现了不强依赖于 `proxy` 配置。 在 [mockMiddleware.ts](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/main/src/mockMiddleware.ts#L57-L63) ：
```ts
const { httpProxies } = ensureProxies(config.server.proxy || {})
  const prefix = toArray(options.prefix)
  const proxies = [...prefix, ...httpProxies]
```
这部分合并了 `proxy` 和 `prefix` 配置。
而使用 `proxy` 和 使用 `prefix` 的不同在于， `proxy` 配置的在插件内判断跳过后，`next` 进入的是 `http-proxy` 的代理，
而 `prefix`配置的 则 `next` 后为 `404`请求。

> 无法区分哪些是接口请求，哪些是资源请求，等于是允许在 *.mock.js 文件中拦截全部请求，也不太合适。

关于这点其实不用担心，在 [baseMiddleware.ts#L62-L67](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/main/src/baseMiddleware.ts#L62-L67):
```ts
if (
      !pathname
      || proxies.length === 0
      || !proxies.some(context => doesProxyContextMatchUrl(context, req.url!))
    )
      return next()
```
做的第一次请求过滤时， 如果 合并后的 `proxies` 为空，则是直接跳过了 插件后续的所有处理。

而且不用管哪些是接口请求哪些是资源请求， mock 本身就应该是包括 资源 也可以被模拟，比如说模拟一个可以被下载的文件链接。

> 随便配置一个无效的 proxy 就能继续走后续 mock 流程了

其实这点也不用担心，在 第二次过滤 [baseMiddleware.ts#L71-L74](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/main/src/baseMiddleware.ts#L71-L74):
```ts
const mockUrls = matchingWeight(Object.keys(mockData), pathname, priority)
 if (mockUrls.length === 0)
    return next()
```
是首先从 mock 配置中找出 满足 当前请求的 mock urls 集合，空时也是直接跳过了，然后在 第三次过滤 [baseMiddleware.ts#L89-L120](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/main/src/baseMiddleware.ts#L89-L120)， 进一步校验了各种请求相关的数据，不满足也是直接跳过了。

即，插件内部只认 在 `*.mock.*` 中声明的 url 规则，即使 `proxy` 随便配置了，但是 rul 规则没有被命中，一律都不会被处理。

> 也许应该在检测到 proxy 和 prefix 都未配置时，打印一个警告提醒一下用户？

`proxy` 和 `prefix` 都未配置时，相当于 插件本身不做任何事情，在第一次过滤时，所有请求在插件内部都被跳过了。
相当于插件对 `http`请求不做任何事情，这时候做的 警告提醒，或许是 提醒用户 未正确配置插件。

**Comment by pfdgithub** [comment]
> proxy 和 prefix 都未配置时，相当于 插件本身不做任何事情，在第一次过滤时，所有请求在插件内部都被跳过了。
> 相当于插件对 http请求不做任何事情，这时候做的 警告提醒，或许是 提醒用户 未正确配置插件。

代码中的几处检查点，我也看到了，所以提议输出一个警告信息。
我也是发现插件完全没有触发mock规则，才去翻代码发现这一点的。

**Comment by pengzhanbo** [comment]
添加一个警告输出有助于帮助使用插件，我补充下这块日志输出。
