### ISSUE TITLE
websocket不成功

### ISSUE THREAD

**Issue by livizy** [pengzhanbo/vite-plugin-mock-dev-server#70]
搞不清楚websocket如何配置，才能使用？

**Comment by pengzhanbo** [comment]
1. 在 vite 中 引入 插件，并配置 [wsPrefix](https://vite-plugin-mock-dev-server.netlify.app/guide/plugin-config#wsprefix)
```ts
// vite.config.ts
import { defineConfig } from 'vite'
import mockDevServerPlugin from 'vite-plugin-mock-dev-server'

export default defineConfig({
  plugins: [
    mockDevServerPlugin({
      wsPrefix: ['^/ws-api'], // 配置你的 websocket 请求前缀
    }),
  ]
})
```
2. 编写 `*.mock.ts`
   文档中有一个 [聊天室的示例](https://vite-plugin-mock-dev-server.netlify.app/examples/websocket)
```ts
// *.mock.ts  基础示例
import type { MockRequest } from 'vite-plugin-mock-dev-server'
import { defineMock } from 'vite-plugin-mock-dev-server'

export default defineMock({
  url: '/ws-api/socket',
  ws: true,   // 必须声明  ws 为 true
  setup(wss) {
    wss.on('connection', (ws, _req: MockRequest) => {
      // req.query
      // req.params
      // req.getCookie
      ws.on('message', (raw) => {
        const message = JSON.parse(String(raw))

        console.log(message)
      })
      ws.send(JSON.stringify({ type: 'connected123' }))
    })
  },
})
```
3. 在 客户端代码中， 建立连接
```ts
const ws = new WebSocket('ws://localhost:5173/ws-api/socket')
ws.addEventListener('open', () => {
  // 连接建立成功， do something
})
ws.addEventListener('message', () => {
  // 接收来自服务端的消息， do something
})
ws.send('message') // 向服务端发送消息
```

----

在 `*.mock.ts` 配置中， `setup(wss, { onCleanup }) {}` 方法 用于配置 服务器端的 `wss` 行为。

其中， `wss` 是 `WebSocketServer`。 通过 `connection` 事件监听是否有 客户端发起 ws 连接，并在回调函数中获取 ws 实例 和 request 实例。 

请查阅 [`ws`文档](https://github.com/websockets/ws)

**Comment by livizy** [comment]
server.proxy怎么配置？

**Comment by pengzhanbo** [comment]
> server.proxy怎么配置？
> 
> 我是用apifox测试的：ws://localhost:5173/ws-api/socket

`server.proxy` 不需要额外的 ws 配置了。 因为 `server.proxy[xxx].ws = true` 和 插件内的 ws mock
都需要 使用 http server 的 upgrade 事件，会消费当前请求连接，导致产生冲突。因此，当配置了 插件的 `wsPrefix` 选项，插件内会检测 `server.proxy` 是否存在冲突，会将 `server.proxy` 中 `ws` 相关的 配置 冲突的部分 过滤排除。

**Comment by livizy** [comment]
那server.proxy，到底改怎么办？

**Comment by pengzhanbo** [comment]
@livizy
这个警告仅是提示未配置 没有配置 http 相关的 proxy， 可以忽略。
在 apifox 中， 建立 连接 不能使用 `ws://localhost:5173`，你应该使用 IP 进行连接。

**Comment by livizy** [comment]
请教一下，如何可以调试呢？

**Comment by livizy** [comment]
我指的是，如何在这个setup中下断点调试。

**Comment by pengzhanbo** [comment]
emmm... 🤔
其实这个插件是依托于 vite 的， 而 vite 是在 nodejs 环境中的， 即 nodejs 的 程序如何进行 断点调式，这个插件也同样如此，并无本质上的区别。 大多出时候使用 `console.log` 查看日志输出都可以满足需求，而且插件内部也做了 针对于 编译时的错误日志输出、运行时的错误日志输出，而且大部分错误都不会导致 服务中断停止，开发时的调试应该挺容易的。
