### ISSUE TITLE
"[ERROR] Invalid define value (must be an entity name or valid JSON syntax)"... when JSON object is the value

### ISSUE THREAD

**Issue by busticated** [pengzhanbo/vite-plugin-mock-dev-server#71]
hi there :wave:

thanks for this great tool and apologies for the english here 🙏 

with a vite configuring like this:

```js
define: {
    'import.meta.env.__X__': JSON.stringify({ my: 'object' )),
},
```

i get an error:

```
✘ [ERROR] Invalid define value (must be an entity name or valid JSON syntax): {"BASE_URL":"/","MODE":"development","DEV":true,"PROD":false,"__X__":{\"my\":\"object\}"}

Error: Build failed with 1 error:
error: Invalid define value (must be an entity name or valid JSON syntax): {"BASE_URL":"/","MODE":"development","DEV":true,"PROD":false,"__X__":{\"my\":\"object\}"}
    at failureErrorWithLog (/Users/me/code/my-app/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/me/code/my-app/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/Users/me/code/my-app/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/Users/me/code/my-app/node_modules/esbuild/lib/main.js:1057:7)
    at /Users/me/code/my-app/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/Users/me/code/my-app/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/Users/me/code/my-app/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/Users/me/code/my-app/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

naively, i think the issue is caused by re-writing the user define entries ([here](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/commit/92d79dd11133b670de785e2d927852e49f39faff#diff-1ed00a29b9bf1ec50c4ac3b4b786a7833e31f53e16fcb338e5b974d929e59131R36)). in cases where the parsed value is an object, esbuild errors. 

ideally user defines wouldn't be edited, just passed thru as they were set. 

also see: https://github.com/pengzhanbo/vite-plugin-mock-dev-server/issues/31

**Comment by busticated** [comment]
if i change [this line](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/c01a129d90b1b893cfcd20c8e89002bdf16e5995/src/define.ts#L37) to:

```diff
-        JSON.parse(val)
+        JSON.parse(val + "INVALID-JSON");
```

my local setup seems to work fine 🤔

**Comment by pengzhanbo** [comment]
I appreciate your discovering this issue and providing a fix.

However, after testing, it appears that the fix only addresses part of the problem. 

Currently, the plugin's processing of `define` is forked from `vite@4` and has not yet been updated to `vite@5`, leading to issues with compatibility. I have re-referenced the relevant code in `vite@5` and rewritten the code in this part of the plugin.

After testing, this issue and other potential scenarios have been successfully resolved.

**Comment by busticated** [comment]
> After testing, this issue and other potential scenarios have been successfully resolved.

great! thank you very much 🙏 

i'll test the updated code once it's released 👍

**Comment by busticated** [comment]
tested - works great - thanks again 🙏🙌👏🚀

**Comment by busticated** [comment]
oh. i just noticed that there's a strange log item output now:

```
3:45:13 PM [vite:mock] No proxy was configured, mock server will not work. See https://vite-plugin-mock-dev-server.netlify.app/guide/usage
```

seems to be coming from [here](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/2c012d970732d60120d234ed93348ef864b1ce08/src/mockMiddleware.ts#L68). in my case, i'm not using websockets so maybe that's causing it? regardless, everything seems to work fine despite the log message suggesting it should not 🤷‍♂️

**Comment by pengzhanbo** [comment]
yes, i see. I made a mistake.

I re-published a minor version to fix it.
