### ISSUE TITLE
[bug:]Cannot start service: Host version "0.19.8" does not match binary version "0.18.17"

### ISSUE THREAD

**Issue by mortalYoung** [pengzhanbo/vite-plugin-mock-dev-server#73]
# Version
- Vite: 4.4.9
- vite-plugin-mock-dev-server: 1.4.0
- esbuild: 0.18.17&0.19.8

# Reason
Maybe the incompatible esbuild version cause this problem.[I'm not sure now]

Would you mind set esbuild to peerDep or other ways to keep esbuild's version unique in project

I found the 4.x vite was still use 0.18.x esbuild

> "dependencies": {
>    "esbuild": "^0.18.10",
>    "postcss": "^8.4.27",
>    "rollup": "^3.27.1"
>  },

**Comment by pengzhanbo** [comment]
Can you tell me the relevant information of your environment, which package manager you use, and what the version number is?

**Comment by mortalYoung** [comment]
> Can you tell me the relevant information of your environment, which package manager you use, and what the version number is?

- pnpm: 6.35.1
- Node.js: 18.16.0

**Comment by pengzhanbo** [comment]
The version of pnpm is too low, please upgrade it to version `7+` or `8+`

see [pnpm installation](https://pnpm.io/installation#using-corepack)
