### ISSUE TITLE
请问支持生产环境吗？有没有相关例子

### ISSUE THREAD

**Issue by lin-97** [pengzhanbo/vite-plugin-mock-dev-server#77]
### Description

请问支持生产环境吗？

### Suggested solution

请问支持生产环境吗？

**Comment by pengzhanbo** [comment]
[mock 服务部署](https://vite-plugin-mock-dev-server.netlify.app/guide/mock-service)
我不确定这是否满足你的生产环境的需求。

首先这个插件不会往你的项目构建产物中注入任何额外的代码，这是为了避免对你的项目产生污染。但还是额外提供了一个 `build` 选项，将会在你的 构建输出目录中生成一个独立的 `mockServer` 目录，它是一个轻量的 node 服务，你可以在
任何支持部署 node 应用的 服务器上部署并启动它，然后通过中间代理服务将你的生产接口进行转发，即可使用 mock 服务数据。
