### ISSUE TITLE
The CJS build of vite-plugin-mock-dev-server's Node API is deprecated

### ISSUE THREAD

**Issue by RockyF** [pengzhanbo/vite-plugin-mock-dev-server#78]
### Bug 描述

安装了最新的1.5.0的版本，报错如下：
`The CJS build of vite-plugin-mock-dev-server's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.`

### 系统环境

```markdown
- OS: macOS 13.6.6
- Node: v18.19.0
- packageManager: yarn
- vite: 4.5.0
- vite-plugin-mock-dev-server: 1.5.0
```

### Logs

> yarn run dev --host
yarn run v1.22.19
$ vite --host
The CJS build of vite-plugin-mock-dev-server's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v4.5.0  ready in 579 ms

  ➜  Local:   http://localhost:5173
  ➜  Network: http://192.168.8.18:5173
  ➜  Network: http://0.0.1.1:5173
  ➜  press h to show help

**Comment by pengzhanbo** [comment]
这个是插件给出的提示，并不是报错。

vite 从 v5 版本开始，逐步 [废弃 `CommonJS`](https://cn.vitejs.dev/guide/migration.html#deprecate-cjs-node-api) 。因此，插件也是跟随 vite 的版本更新变动，逐步废弃 `CommonJS`, 只是目前的版本依然保留同时导出 `ESM/CJS` ，在检测到使用 `CJS` 导入插件时给出这个提示，但不影响使用。

 nodeJS 社区在推动逐步废弃 `CommonJS` ，以及随着 `vite` 的版本变动，个人给出一点小小的建议，也许你是时候将你的项目从 `cjs` 迁移到 `esm` 了，可以参考 这份 [文档](https://cn.vitejs.dev/guide/migration.html#deprecate-cjs-node-api) 对项目进行改造。不过目前你不做任何改动也依然可以正常使用插件的所有功能，即使 vite到 v6 版本后完全废弃 `cjs`，插件还是会在很长一点时间内保留 `cjs`的导出以保证对旧版本的兼容。

**Comment by RockyF** [comment]
> 这个是插件给出的提示，并不是报错。
> 
> vite 从 v5 版本开始，逐步 [废弃 `CommonJS`](https://cn.vitejs.dev/guide/migration.html#deprecate-cjs-node-api) 。因此，插件也是跟随 vite 的版本更新变动，逐步废弃 `CommonJS`, 只是目前的版本依然保留同时导出 `ESM/CJS` ，在检测到使用 `CJS` 导入插件时给出这个提示，但不影响使用。
> 
> nodeJS 社区在推动逐步废弃 `CommonJS` ，以及随着 `vite` 的版本变动，个人给出一点小小的建议，也许你是时候将你的项目从 `cjs` 迁移到 `esm` 了，可以参考 这份 [文档](https://cn.vitejs.dev/guide/migration.html#deprecate-cjs-node-api) 对项目进行改造。不过目前你不做任何改动也依然可以正常使用插件的所有功能，即使 vite到 v6 版本后完全废弃 `cjs`，插件还是会在很长一点时间内保留 `cjs`的导出以保证对旧版本的兼容。

嗯，我后来也查到了，谢谢
