### ISSUE TITLE
How to set a global mock config

### ISSUE THREAD

**Issue by byv55f5f5** [pengzhanbo/vite-plugin-mock-dev-server#79]
### Describe the bug

I want to set a delay to every mock.

The `server.proxy` setting in `vite.config.js` is:

```js
    server: {
      // ...
      proxy: {
        '^/api/v[0-9]/': {
          target: HTTP_API_URI,
          changeOrigin: true,
          ws: false
        }
      }
      // ...
    },
```

And I define a mock on the top of all mocks:
```js
{
  url: '/api/(.*)',
  method: ['DELETE', 'GET', 'HEAD', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'TRACE'],
  delay: 0.5 * ONE_SECOND,
  response(_, __, next) {
    next()
  }
}
```

I've tried to log something before `next()`. But nothing is printed.

### Environment

```markdown
- OS: macOS Sonoma 14.4.1
- Node: v20.12.0
- packageManager: yarn 1.22.21
- vite: 5.1.5
- vite-plugin-mock-dev-server: 1.4.7
```

**Comment by pengzhanbo** [comment]
If you want to set a delay for every mock, you should use [`createDefineMock(transformer)`](https://vite-plugin-mock-dev-server.netlify.app/en/guide/create-define-mock) :

`shared.ts`
```ts
export const defineDelayMock = createDefineMock((mock) => {
  mock.delay = 0.5 * ONE_SECOND
})
```

`*.mock.ts`
```ts
import { defineDelayMock } from './shared'

export default defineDelayMock({
  url: '/api/xxx',
  // more
})
```

defineDelayMock will add a `delay` option to every mock.

----

> And I define a mock on the top of all mocks:
>
> ```ts
> {
>   url: '/api/(.*)',
>   method: ['DELETE', 'GET', 'HEAD', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'TRACE'],
>   delay: 0.5 * ONE_SECOND,
>   response(_, __, next) {
>     next()
>   }
> }
> ```

The plugin will re-sort the configured URL rules. In fact, ` /api/(.*)` will be placed at the lowest level of matching, serving as a fallback mock that is only used to respond to requests when no other rules are satisfied.

**Comment by byv55f5f5** [comment]
Thank @pengzhanbo for replying quickly.
