### ISSUE TITLE
是否可以支持测试环境部署？

### ISSUE THREAD

**Issue by kenixFog** [pengzhanbo/vite-plugin-mock-dev-server#8]
大佬好~项目前期可能只是想简单的纯前端部署展示，不想涉及后端，比如打包后部署到nginx上，通过mock数据进行简单的展示~是否可以提供对该场景的支持？

**Comment by pengzhanbo** [comment]
这个场景我在春节前就有考虑过的，但是还没确定支持该场景的方案。

因为考虑到 mock 文件是支持引入 node 模块的，所以不能直接打包到前端代码中，在我的初步设想中，是在插件中提供一个 cli 工具，构建出一个可独立部署的轻型服务，或者提供一个中间件的方式来支持这种场景。但是我不确定这种方案是否能够满足通用场景，比如测试环境的服务器的部署权限、测试环境的服务器是否支持node环境等。

在接下来的一段时间我会尝试实现这个方案，但我暂时不能给你一个明确的实现该场景支持的具体时间。

一种临时的解决方案是，本插件是支持 `vite preview` 模式的，也就是说，当你通过 `vite build` 构建好你的包后，你可以通过 `vite preview` 命令来启动一个预览模式来访问你的应用，这个时候，`mock server` 也会启动，预览模式下就可以正常的看到mock数据展示的应用。如果对环境没有要求，那么可以将你的本地环境的预览模式访问地址用于展示，如果对环境有要求，可以将你的项目推送到测试环境中启动预览模式，再通过 nginx进行反向代理。

**Comment by kenixFog** [comment]
> 这个场景我在春节前就有考虑过的，但是还没确定支持该场景的方案。
> 
> 因为考虑到 mock 文件是支持引入 node 模块的，所以不能直接打包到前端代码中，在我的初步设想中，是在插件中提供一个 cli 工具，构建出一个可独立部署的轻型服务，或者提供一个中间件的方式来支持这种场景。但是我不确定这种方案是否能够满足通用场景，比如测试环境的服务器的部署权限、测试环境的服务器是否支持node环境等。
> 
> 在接下来的一段时间我会尝试实现这个方案，但我暂时不能给你一个明确的实现该场景支持的具体时间。
> 
> 一种临时的解决方案是，本插件是支持 `vite preview` 模式的，也就是说，当你通过 `vite build` 构建好你的包后，你可以通过 `vite preview` 命令来启动一个预览模式来访问你的应用，这个时候，`mock server` 也会启动，预览模式下就可以正常的看到mock数据展示的应用。如果对环境没有要求，那么可以将你的本地环境的预览模式访问地址用于展示，如果对环境有要求，可以将你的项目推送到测试环境中启动预览模式，再通过 nginx进行反向代理。

尝试了几个插件，发现有个插件是可以适用以上场景的，vite-plugin-mock，具体的思路没有深究，大佬可以看看，不知是否能有所帮助~

**Comment by pengzhanbo** [comment]
@kenixFog 思路不同，vite-plugin-mock 这个插件是不支持引入node模块的，并且使用 `mockjs`作为核心依赖，以及其他的客户端支持的模块。

[vite-plugin-mock#注意事项](https://github.com/vbenjs/vite-plugin-mock/blob/main/README.zh_CN.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9) 

将mock的代码打包到构建包中，用于测试环境，或者是用于做自动化测试，如 e2e 测试，其测试结果是不可靠的，因为测试包和生产包不一致，这也是为什么我在本插件的 [Features](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/blob/main/README.zh-CN.md#%E7%89%B9%E6%80%A7) 强调 对客户端代码无侵入的原因。 

vite-plugin-mock 在开发环境下，通过mockjs包装mock数据：[createMockServer](https://github.com/vbenjs/vite-plugin-mock/blob/main/src/createMockServer.ts#L100),  在生产环境通过 mockjs 拦截`xhr` 返回 mock数据。这种方式虽然能够覆盖多数的json格式的mock数据场景，但是也使得mock失去了灵活性和可扩展性，也无法覆盖到更多的场景，比如 原生表单提交、文件的上传/下载、gRPC等。

当然这些也是与插件在设计之初所做的取舍有关，要支持能够将代码直接打包内联到前端构建包中，必然要放弃很多场景的支持，而专注于一部分通用性强的场景。

在我的理解之中， mock 数据的需求，更多是集中在 开发时、自动化测试时 ，不会用于生产，那么在 vite dev/preview 下通过 vite内部的 http server 提供 mock ，放弃将mock文件打包到前端构建包中，而换取node模块带来的更多的灵活性可扩展性，是一个更好的选择。

而且 `vite preview` 模式也能够在一定程度上提供 页面展示的能力，在后续的计划中，加上打包小型可独立部署mock服务，或 mock中间件提供集成，再通过http server做反向代理，基本可以覆盖到纯前端展示的场景。而我对这一方案的不确定性，则是来于其对环境、对部署、对 http server相关知识，这些对插件使用者是有要求的，这可能不会被使用者接受。

**Comment by pengzhanbo** [comment]
@kenixFog 在 `v0.3.17` 版本中，已实现了 可构建独立部署的mock server，可用于满足对应场景的支持。
