### ISSUE TITLE
无法请求到数据

### ISSUE THREAD

**Issue by how2j-coder** [pengzhanbo/vite-plugin-mock-dev-server#80]
### Bug 描述

版本：
"node": 18.19.0
 "typescript": "^5.2.2",
  "vite": "^5.2.0",
"vue": "^3.4.21",
  "vite-plugin-mock-dev-server": "^1.5.0",

`api.mock.ts `内容：
```
import { defineMock } from "vite-plugin-mock-dev-server";

export default defineMock({
  url: "/api/test",
  body: {
    name: "Mark",
    age: 18,
  },
});

```
`vite.config.ts` 内容：
```
import mockDevServerPlugin from "vite-plugin-mock-dev-server";
export default defineConfig(() => {
  return {
    plugins: [vue(), mockDevServerPlugin()],
    build: {
      outDir: "dist", // 指定打包路径，默认为项目根目录下的 dist 目录
.......
```

当我请求 http://localhost:5173/api/test时 ：
接口返回 HTML内容：
```
<!doctype html>
<html lang="zh">
  <head>
    <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + Vue + TS</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
```

### 系统环境

```markdown
- Node: 18.19.0
- packageManager: pnpm
- vue: 3.4.1
- vite: 5.2.0
- vite-plugin-mock-dev-server: 1.5.0
```

**Comment by how2j-coder** [comment]
> `api.mock.ts` 是否放在项目上下文的 `mock` 目录中？ 插件默认仅从 mock 目录中读取 `*.mock.*` 文件

![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/168560301/d7e5a204-24f3-423e-b489-ae6ae145813f)

我用`pnpm create vite my-vue-app --template vue-ts` 创建了个新的项目，按照`vite-plugin-mock-dev-server`文档去配置，还是一样的结果，但是使用`react-ts`就没问题

**Comment by pengzhanbo** [comment]
还有一个关键配置是，在 `vite.config.ts` 中：

```ts
server: {
    proxy: {
      '^/api': { target: 'http://example.com/' }
    }
  }
```
是否有这个配置？

**Comment by how2j-coder** [comment]
> 还有一个关键配置是，在 `vite.config.ts` 中：
> 
> ```ts
> server: {
>     proxy: {
>       '^/api': ''
>     }
>   }
> ```
> 
> 是否有这个配置？

![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/168560301/58e4987c-801d-4b64-9aa7-30d46df9dea5)

**Comment by pengzhanbo** [comment]
emmmm, 这就比较奇怪了，可否通过这个项目，做一个 最小重现，可以在 <https://stackblitz.com/> 上，或者提供一个项目压缩包给我？

**Comment by how2j-coder** [comment]
emm 我刚刚看到了问题了我的请求中的baseUrl写错了 麻烦你了
