### ISSUE TITLE
多个 vite 配置文件的情况下，server.proxy 配置后不生效

### ISSUE THREAD

**Issue by YILS-LIN** [pengzhanbo/vite-plugin-mock-dev-server#82]
### Bug 描述

![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/62397373/c968ef6c-5c71-49bc-94a6-45933896be57)
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/62397373/f186b57e-80d1-4291-a267-2faae563f5ab)
![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/62397373/0b2afb7e-34ac-48ce-8a46-ead1c54350c3)

### 系统环境

```markdown
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900HX
    Memory: 15.94 GB / 31.74 GB
  Binaries:
    Node: 18.19.1
    Yarn: 1.22.19
    npm: 10.2.4
    pnpm(use): 8.9.2
  Browsers:
    Edge: Chromium (125.0.2535.79)
    Internet Explorer: 11.0.22621.3527
```

### Logs

[vite:mock] No proxy was configured, mock server will not work. See https://vite-plugin-mock-dev-server.netlify.app/guide/usage

**Comment by YILS-LIN** [comment]
感谢回复，我尝试了改写为 `mergeConfig(baseConfig, devConfig, false)` 的方式，仍然存在这个提示，mock没有生效，于是我从新建的项目中测试后，发现**可能不是合并配置导致的问题**，因此我使用 StackBlitz 放置了一个最小的问题复现：

在线运行地址：https://stackblitz.com/edit/vitejs-vite-rx44wx?file=vite.config.js

控制台完整截图：

![image](https://github.com/pengzhanbo/vite-plugin-mock-dev-server/assets/62397373/14c4b98f-778c-49bb-a6ed-84db3fabd573)


使用配置文件：

```javascript
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import mockDevServerPlugin from 'vite-plugin-mock-dev-server';

// https://vitejs.dev/config/
export default defineConfig({
  server: {
    open: false,
    fs: {
      strict: true,
    },
    proxy: {
      '/api': {
        // 配置需要代理的路径 --> 这里的意思是代理http://localhost:80/api/后的所有路由
        target: 'http://localhost:8080', // 目标地址 --> 服务器地址
        changeOrigin: true, // 允许跨域
        ws: true, // 允许websocket代理
        // 重写路径 --> 作用与vue配置pathRewrite作用相同
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
  plugins: [
    vue(),
    mockDevServerPlugin({
      prefix: [],
      wsPrefix: [],
      include: ['src/mock/**/*.mock.{js,ts,cjs,mjs,json,json5}'],
      exclude: undefined,
      log: 'info',
      reload: true,
      cors: true,
      formidableOptions: undefined,
      cookiesOptions: undefined,
      bodyParserOptions: undefined,
      priority: undefined,
    }),
  ],
});

```

**Comment by pengzhanbo** [comment]
emmmm... 我仔细看了 最小重现中的配置，发现了问题所在， 你在 `server.proxy` 中， 在 `/api` 中配置了 `ws:true`, 不仅插件会认为 `/api` 开头的都是 websocket 连接， 而且 vite 也一样不会对 `/api` 开头的 http 请求进行代理转发。

如果是 http 请求，请删除 `ws:true` 。

**Comment by YILS-LIN** [comment]
😂 问题竟然在这…… 是我配置错误，实在抱歉。
