### ISSUE TITLE
body内容某些情况下存在JSON解析失败

### ISSUE THREAD

**Issue by itmanyong** [pengzhanbo/vite-plugin-mock-dev-server#96]
### Bug 描述

- 以下是body数据，content-type为json
```bash
[
    {
        "avatar": "https://avatars.githubusercontent.com/u/40507263",
        "nickName": "Miss Andrea Jacobi",
        "username": "Reece20",
        "password": "e10adc3949ba59abbe56e057f20f883e",
        "email": "Bernhard.Runte@yahoo.com",
        "phone": "1-377-900-8241",
        "status": "ENABLE",
        "role_code": [],
        "menu_code": [],
        "remark": "Conservo tersus corroboro tergo quaerat ratione decens blanditiis cumque vespillo.",
    },
    {
        "avatar": "https: //avatars.githubusercontent.com/u/34169353",
        "nickName": "Moses Bashirian",
        "username": "Loy.Abbott44",
        "password": "e10adc3949ba59abbe56e057f20f883e",
        "email": "Sheldon23@yahoo.com",
        "phone": "1-351-341-7620",
        "status": "DISABLE",
        "role_code": [],
        "menu_code": [],
        "remark": "Arguo solum auxilium vorax.",
    }
]
```
- 模拟服务器拦截到路由后，当读取body时，会报JSON解析失败，如下
![image](https://github.com/user-attachments/assets/6016eeec-dd6a-46c2-b2bc-8c3df9679b5a)
- 传递的数据通过JSON.parse和JSON.stringify均能正常转换，貌似bodyParser.json有什么不同于JSON转换的规则吗
![image](https://github.com/user-attachments/assets/99882e05-714d-4741-ab7e-483787b26ca5)

### 系统环境

```markdown
- OS:win10 pro x64
- Node:20.16.0
- packageManager:pnpm 9.7.1
- vite:5.4.2
- vite-plugin-mock-dev-server:^1.7.1
```

### Logs

SyntaxError: Expected double-quoted property name in JSON at position 485
    at JSON.parse (<anonymous>)
    at exports.parse (D:\Administrator\MyDocuments\GitHub\vite-vue-templte-js\node_modules\.pnpm\@hapi+bourne@3.0.0\node_modules\@hapi\bourne\lib\index.js:19:22)
    at parse (D:\Administrator\MyDocuments\GitHub\vite-vue-templte-js\node_modules\.pnpm\co-body@6.2.0\node_modules\co-body\lib\json.js:59:19)
    at module.exports [as json] (D:\Administrator\MyDocuments\GitHub\vite-vue-templte-js\node_modules\.pnpm\co-body@6.2.0\node_modules\co-body\lib\json.js:43:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseReqBody (file:///D:/Administrator/MyDocuments/GitHub/vite-vue-templte-js/node_modules/.pnpm/vite-plugin-mock-dev-server@1.7.1_esbuild@0.23.1_vite@5.4.2_less@4.2.0_lightningcss@1.26.0_sass@1.77.8_terser@5.31.6_/node_modules/vite-plugin-mock-dev-server/dist/chunk-TTKDHWOT.js:174:14)
    at async file:///D:/Administrator/MyDocuments/GitHub/vite-vue-templte-js/node_modules/.pnpm/vite-plugin-mock-dev-server@1.7.1_esbuild@0.23.1_vite@5.4.2_less@4.2.0_lightningcss@1.26.0_sass@1.77.8_terser@5.31.6_/node_modules/vite-plugin-mock-dev-server/dist/chunk-TTKDHWOT.js:374:21 {
  status: 400,
  body: '[\r\n' +
    '    {\r\n' +
    '        "avatar": "https://avatars.githubusercontent.com/u/40507263",\r\n' +
    '        "nickName": "Miss Andrea Jacobi",\r\n' +
    '        "username": "Reece20",\r\n' +
    '        "password": "e10adc3949ba59abbe56e057f20f883e",\r\n' +
    '        "email": "Bernhard.Runte@yahoo.com",\r\n' +
    '        "phone": "1-377-900-8241",\r\n' +
    '        "status": "ENABLE",\r\n' +
    '        "role_code": [],\r\n' +
    '        "menu_code": [],\r\n' +
    '        "remark": "Conservo tersus corroboro tergo quaerat ratione decens blanditiis cumque vespillo.",\r\n' +
    '    },\r\n' +
    '    {\r\n' +
    '        "avatar": "https: //avatars.githubusercontent.com/u/34169353",\r\n' +
    '        "nickName": "Moses Bashirian",\r\n' +
    '        "username": "Loy.Abbott44",\r\n' +
    '        "password": "e10adc3949ba59abbe56e057f20f883e",\r\n' +
    '        "email": "Sheldon23@yahoo.com",\r\n' +
    '        "phone": "1-351-341-7620",\r\n' +
    '        "status": "DISABLE",\r\n' +
    '        "role_code": [],\r\n' +
    '        "menu_code": [],\r\n' +
    '        "remark": "Arguo solum auxilium vorax.",\r\n' +
    '    }\r\n' +
    ']'
}

**Comment by pengzhanbo** [comment]
emmmm....

`co-body` 内部调用的 `@hapi/bourne`，它也是包装的 `JSON.parse`。

实际上日志上已经写的很清楚了，你的 JSON 字符串格式有问题。我粗略的看了下，你的每个 `remark` 字段的值后面，都多了一个 `,` 。

```diff
[
    {
        "avatar": "https://avatars.githubusercontent.com/u/40507263",
        "nickName": "Miss Andrea Jacobi",
        "username": "Reece20",
        "password": "e10adc3949ba59abbe56e057f20f883e",
        "email": "Bernhard.Runte@yahoo.com",
        "phone": "1-377-900-8241",
        "status": "ENABLE",
        "role_code": [],
        "menu_code": [],
-        "remark": "Conservo tersus corroboro tergo quaerat ratione decens blanditiis cumque vespillo.",
+        "remark": "Conservo tersus corroboro tergo quaerat ratione decens blanditiis cumque vespillo."
    },
    {
        "avatar": "https: //avatars.githubusercontent.com/u/34169353",
        "nickName": "Moses Bashirian",
        "username": "Loy.Abbott44",
        "password": "e10adc3949ba59abbe56e057f20f883e",
        "email": "Sheldon23@yahoo.com",
        "phone": "1-351-341-7620",
        "status": "DISABLE",
        "role_code": [],
        "menu_code": [],
-        "remark": "Arguo solum auxilium vorax.",
+        "remark": "Arguo solum auxilium vorax."
    }
]
```
