### ISSUE TITLE
v1.7.2 热更新失效

### ISSUE THREAD

**Issue by LiMao00** [pengzhanbo/vite-plugin-mock-dev-server#98]
### Bug 描述

v1.7.2 热更新失效，修改 app.mock.ts 的数据没有反应，刷新没反应，必须重新 dev 项目。退回到之前用过的 v1.3.4 可以正常使用

### 系统环境

```markdown
- OS:
- Node:v18.16.0
- packageManager:
- vite:5.4.7
- vite-plugin-mock-dev-server:v1.7.2
```

**Comment by LiMao00** [comment]
1.7.1 正常

**Comment by pengzhanbo** [comment]
`chokidar@4` 移除了 glob 模式匹配的支持，我之前在升级依赖时没有注意到这一点。由于这个更新带来的影响有点大，我打算先将其回退到 `chokidar@3.6.0` 。后续我在研究下 chokidar 的升级方案。
